config/routes.rb
Rails.application.routes.draw do
  root to: 'vue_crud_data#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :vue_crud_data, only: [:index, :new, :create, :update, :destroy]

  # get 'vue_crud_data/index'
  get    'vue_crud_data/index'
  get    'vue_crud_data/new',  to: 'vue_crud_data#new',     as: 'new_vue_crud_data'
  post   'vue_crud_data',      to: 'vue_crud_data#create'
  put    'vue_crud_data/:id',  to: 'vue_crud_data#update'
  delete 'vue_crud_data/:id',  to: 'vue_crud_data#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/vue_crud_data_bk.rb
class VueCrudDataBk < ApplicationRecord
end

app/models/vue_crud_datum.rb
class VueCrudDatum < ApplicationRecord
  validates :name, length: { maximum: 20 }, presence: true
  validates :comment, length: { maximum: 140 }, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/vue_crud_data_controller.rb
class VueCrudDataController < ApplicationController
  before_action :set_datum, only: [:update, :destroy]

  def index
    @data = VueCrudDatum.all.order(updated_at: 'DESC')

    respond_to do |format|
      # html用
      format.html
      # json用
      format.json { render json: @data }
    end
  end

  # 全て初期化
  def new
    ActiveRecord::Base.transaction do
      # 高速削除
      ActiveRecord::Base.connection.execute("TRUNCATE TABLE vue_crud_data;")
      # 高速挿入
      ActiveRecord::Base.connection.execute("INSERT INTO vue_crud_data SELECT * FROM vue_crud_data_bks;")
    end

    redirect_to root_url
  end

  def create
    @datum = VueCrudDatum.new(datum_params)

    respond_to do |format|
      if @datum.save
        format.json { render json: { registration: "Ajaxによるデータの登録が成功しました。",
           id: @datum.id, name: @datum.name, comment: @datum.comment, updated_at: @datum.updated_at } }
      else
        format.json { render json: { registratio: 'Ajaxによるデータの登録が失敗しました。',
          id: 'error' } }
      end
    end
  end

  def update
    respond_to do |format|
      if @datum.update(datum_params)
        format.json { render json: { registration: "Ajaxによるデータの更新が成功しました。" } }
      else
        format.json { render json: { registration: "Ajaxによるデータの更新が失敗しました。" } }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @datum.destroy
        format.json { render json: { registration: 'Ajaxによるデータの削除が成功しました。' } }
      else
        format.json { render json: { registration: 'Ajaxによるデータの削除が失敗しました。' } }
      end
    end
  end

  private

  def set_datum
    @datum = VueCrudDatum.find(params[:id])
  end

  def datum_params
    params.require(:datum).permit(:name, :comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vue_crud_data_helper.rb
module VueCrudDataHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsVueCRUD</title>
    <meta name="robots" content="noindex, nofollow" />
    <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>

    <% #vue_crud.jsの読み込み %>
    <%= javascript_pack_tag 'vue_crud' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-primary">
      <div class="navbar-brand text-white"><%= "Rails + Vue + AjaxでCRUDのサンプルプロジェクト" %></div>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item"><%= link_to '全て初期化', new_vue_crud_data_path, class: 'nav-link', style: 'color: #fff;' %></li>
      </ul>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
    <br>
    <nav class="container bg-primary p-2 text-center">
      <div class="text-center text-white">
        Vue "CRUD" Sample
      </div>
      <div class="text-center text-white">
        Takeshi Okamoto wrote the code.
      </div>
      <p></p>
    </nav>
  </body>
</html>

app/views/vue_crud_data/index.html.erb
<div id="root"></div>